services:
  koshi-backend:
    build:
      context: ./source_code/backend
      dockerfile: Dockerfile
    container_name: koshi-backend
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./data/koshi.db
      - JWT_SECRET=${JWT_SECRET:-koshi_production_jwt_secret_secure_key_2026_9f83a21bc9e47d108f}
      - AI_API_URL=https://api.openai.com/v1/chat/completions
      - AI_API_KEY=${AI_API_KEY:-}
      - AI_MODEL_NAME=gpt-4o-mini
      - OLLAMA_URL=http://host.docker.internal:11434/v1/chat/completions
    volumes:
      - koshi-data:/app/data
    networks:
      - koshi-internal

  koshi-frontend:
    build:
      context: ./source_code/frontend
      dockerfile: Dockerfile
    container_name: koshi
    restart: unless-stopped
    depends_on:
      - koshi-backend
    networks:
      - koshi-internal
      - proxy-net

volumes:
  koshi-data:

networks:
  koshi-internal:
    driver: bridge
  proxy-net:
    external: true
