"""
Storage for comment attachments.

Uploaded files are the one place where a user hands us bytes that we later hand
to another user's browser, so the rules here are deliberately narrow:

* **An allowlist, not a blocklist.** Only the image and video types below are
  accepted. Anything else is refused, including types that are merely unknown.
* **The client's filename never touches the filesystem.** `stored_name` is
  generated here; the original is kept only as a label. This is what makes path
  traversal (`../../etc/passwd`) impossible rather than merely filtered.
* **The stored content type comes from our table, not from the request.** A
  browser that content-sniffs an "image/png" upload into HTML would give the
  uploader script execution on this origin.
* **The size limit is enforced while streaming.** Trusting `Content-Length`, or
  reading the body and measuring afterwards, both let a large upload exhaust
  memory before the check runs.
"""
import os
import secrets
from typing import Tuple

from fastapi import HTTPException, UploadFile

from app.config import settings

# Extension is chosen by us from the content type, never taken from the upload.
ALLOWED_TYPES = {
    "image/png": ".png",
    "image/jpeg": ".jpg",
    "image/gif": ".gif",
    "image/webp": ".webp",
    "video/mp4": ".mp4",
    "video/webm": ".webm",
    "video/quicktime": ".mov",
}

CHUNK = 1024 * 1024


def upload_dir() -> str:
    os.makedirs(settings.UPLOAD_DIR, exist_ok=True)
    return settings.UPLOAD_DIR


def path_for(stored_name: str) -> str:
    """
    Absolute path for a stored file.

    `stored_name` is generated by `save_upload` and never client-supplied, but
    the basename check stays: it costs nothing and means a future caller that
    passes something else cannot escape the directory.
    """
    if stored_name != os.path.basename(stored_name):
        raise HTTPException(status_code=400, detail="Invalid attachment reference")
    return os.path.join(upload_dir(), stored_name)


async def save_upload(file: UploadFile) -> Tuple[str, str, int]:
    """
    Stream an upload to disk.

    Returns (stored_name, content_type, size_bytes). Raises 400 on a type that
    is not allowed and 413 on one that is too large; a partial file is removed
    rather than left as an orphan.
    """
    content_type = (file.content_type or "").split(";")[0].strip().lower()
    if content_type not in ALLOWED_TYPES:
        raise HTTPException(
            status_code=400,
            detail=(
                f"Unsupported file type '{content_type or 'unknown'}'. "
                f"Allowed: {', '.join(sorted(ALLOWED_TYPES))}"
            ),
        )

    stored_name = f"{secrets.token_hex(16)}{ALLOWED_TYPES[content_type]}"
    target = path_for(stored_name)

    size = 0
    try:
        with open(target, "wb") as out:
            while chunk := await file.read(CHUNK):
                size += len(chunk)
                if size > settings.MAX_UPLOAD_BYTES:
                    raise HTTPException(
                        status_code=413,
                        detail=(
                            "File is larger than the "
                            f"{settings.MAX_UPLOAD_BYTES // (1024 * 1024)} MB limit"
                        ),
                    )
                out.write(chunk)
    except Exception:
        # Never leave a half-written file behind, whether the cause was the size
        # limit or a disk error.
        if os.path.exists(target):
            os.remove(target)
        raise

    if size == 0:
        os.remove(target)
        raise HTTPException(status_code=400, detail="The file is empty")

    return stored_name, content_type, size
